# Generated by Django 3.0.3 on 2020-02-26 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignmodel',
            old_name='created_by',
            new_name='created_by_id',
        ),
        migrations.RenameField(
            model_name='campaignmodel',
            old_name='unit',
            new_name='unit_id',
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='created_by_id',
            field=models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='unit_id',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='campaign.PriceUnitModel'),
        ),
    ]
