# Generated by Django 3.0.3 on 2020-02-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20200226_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.PriceUnitModel'),
        ),
        migrations.AlterField(
            model_name='priceunitmodel',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
