# Generated by Django 3.0.3 on 2020-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donorprofile_fundraiserprofile_mgoprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
