# Generated by Django 3.0.3 on 2020-03-13 01:56

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'campaign_status',
            },
        ),
        migrations.CreateModel(
            name='PriceUnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'campaign_price_unit',
            },
        ),
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('inventory', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None)),
                ('image', models.FileField(null=True, upload_to='')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('modified_by_id', models.ForeignKey(db_column='modified_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('status_id', models.ForeignKey(db_column='status_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='status_code', to='campaign.CampaignStatusModel')),
                ('unit_id', models.ForeignKey(db_column='unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_type', to='campaign.PriceUnitModel')),
            ],
            options={
                'db_table': 'campaign_details',
                'ordering': ['-created_on'],
            },
        ),
    ]
