# Generated by Django 3.0.3 on 2020-03-13 02:57

import campaign.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=campaign.models.upload_image),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_type', to='campaign.PriceUnitModel'),
        ),
    ]
